[server]
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#3182CE"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#4A5568"
textColor = "#1A202C"
font = "sans serif"